version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy_network
    restart: unless-stopped

  # nginx-proxy-manager:
  #   container_name: nginx
  #   image: 'jc21/nginx-proxy-manager:latest'
  #   restart: unless-stopped
  #   expose:
  #     - '80'
  #   volumes:
  #     - ./data:/data
  #   networks:
  #     - nginx-proxy_network
  #   environment:
  #     - "VIRTUAL_HOST=nginx.zairecloud.pt"
  #     - "VIRTUAL_PORT=80"
  #     - "LETSENCRYPT_HOST=nginx.zairecloud.pt"

  acme-companion:
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=joaonunatings@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nginx-proxy_network
    restart: unless-stopped
      
networks:
  nginx-proxy_network:
    external: true